### ISSUE TITLE
boolean type is missing from the permitted data payload

### ISSUE THREAD

**Issue by TeMeta** [cdisc-org/DataExchange-DatasetJson#19]
(raised initially by Tilo Blenk) 
It appears that Boolean types, which are permitted per Dataset-JSON schema, are not included in the list of applicable data types.

This might have been because the example data included no booleans.

`boolean` type needs adding to dataset.ts and json schema refreshed

**Comment by lexjansen** [comment]
Thanks, we can add it to the list of proposed changes listed at: https://wiki.cdisc.org/display/~shume@cdisc.org/Pilot+Feedback+for+Review

Since initially Dataset-JSON is a drop-in replacement for XPT, I think it should be discussed also how boolean values should be interpreted in SAS (Y/N, Yes/No, 1/0)?
